/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-01-16 21:50:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.center;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class centerMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../resources/css/center/centerSearch.css\">\r\n");
      out.write("<style>\r\n");
      out.write("    \r\n");
      out.write("    #centerWrapper {\r\n");
      out.write("    \tmargin: auto;\r\n");
      out.write("    \twidth: 70%;\r\n");
      out.write("    \tmin-height: 800px;\r\n");
      out.write("    \tdisplay: flex;\r\n");
      out.write("    \tjustify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #sidoSelect {\r\n");
      out.write("    \tmargin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    #gugunSelectArea {\r\n");
      out.write("    \t   \t\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    label {\r\n");
      out.write("    \tdisplay: block;\r\n");
      out.write("    \twidth: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <h1>기관찾기</h1>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"centerWrapper\">\r\n");
      out.write("\t    \r\n");
      out.write("\t    <!-- 기관 검색 -->\r\n");
      out.write("\t    <div id =\"selectArea\">\r\n");
      out.write("\t    \t<h2>기관 검색</h2>\r\n");
      out.write("\t\t    <select name=\"sidoSelect\" id=\"sidoSelect\"></select>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\t\t<div id=\"gugunSelectArea\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>    \r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <!-- 기관 목록 -->\r\n");
      out.write("\t    <div id=\"centerListArea\">\r\n");
      out.write("\t    \t<h2>기관 목록</h2>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <div id=\"mapArea\">\r\n");
      out.write("\t    \t\t지도\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    \r\n");
      out.write(" \t\t</div>\r\n");
      out.write("     \r\n");
      out.write("        \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t var sidoArea = [\"시/도 선택\",\"서울특별시\",\"인천광역시\",\"대전광역시\",\"광주광역시\",\"대구광역시\",\"울산광역시\",\"부산광역시\",\"경기도\",\"강원도\",\"충청북도\",\"충청남도\",\"전라북도\",\"전라남도\",\"경상북도\",\"경상남도\",\"제주도\"];\r\n");
      out.write("\t\t  \r\n");
      out.write("\t \t var gugun1 = [\"강남구\",\"강동구\",\"강북구\",\"강서구\",\"관악구\",\"광진구\",\"구로구\",\"금천구\",\"노원구\",\"도봉구\",\"동대문구\",\"동작구\",\"마포구\",\"서대문구\",\"서초구\",\"성동구\",\"성북구\",\"송파구\",\"양천구\",\"영등포구\",\"용산구\",\"은평구\",\"종로구\",\"중구\",\"중랑구\"];\r\n");
      out.write("\t   var gugun2 = [\"계양구\",\"남구\",\"남동구\",\"동구\",\"부평구\",\"서구\",\"연수구\",\"중구\",\"강화군\",\"옹진군\"];\r\n");
      out.write("\t   var gugun3 = [\"대덕구\",\"동구\",\"서구\",\"유성구\",\"중구\"];\r\n");
      out.write("\t   var gugun4 = [\"광산구\",\"남구\",\"동구\",\"북구\",\"서구\"];\r\n");
      out.write("\t   var gugun5 = [\"남구\",\"달서구\",\"동구\",\"북구\",\"서구\",\"수성구\",\"중구\",\"달성군\"];\r\n");
      out.write("\t   var gugun6 = [\"남구\",\"동구\",\"북구\",\"중구\",\"울주군\"];\r\n");
      out.write("\t   var gugun7 = [\"강서구\",\"금정구\",\"남구\",\"동구\",\"동래구\",\"부산진구\",\"북구\",\"사상구\",\"사하구\",\"서구\",\"수영구\",\"연제구\",\"영도구\",\"중구\",\"해운대구\",\"기장군\"];\r\n");
      out.write("\t   var gugun8 = [\"고양시\",\"과천시\",\"광명시\",\"광주시\",\"구리시\",\"군포시\",\"김포시\",\"남양주시\",\"동두천시\",\"부천시\",\"성남시\",\"수원시\",\"시흥시\",\"안산시\",\"안성시\",\"안양시\",\"양주시\",\"오산시\",\"용인시\",\"의왕시\",\"의정부시\",\"이천시\",\"파주시\",\"평택시\",\"포천시\",\"하남시\",\"화성시\",\"가평군\",\"양평군\",\"여주군\",\"연천군\"];\r\n");
      out.write("\t   var gugun9 = [\"강릉시\",\"동해시\",\"삼척시\",\"속초시\",\"원주시\",\"춘천시\",\"태백시\",\"고성군\",\"양구군\",\"양양군\",\"영월군\",\"인제군\",\"정선군\",\"철원군\",\"평창군\",\"홍천군\",\"화천군\",\"횡성군\"];\r\n");
      out.write("\t   var gugun10 = [\"제천시\",\"청주시\",\"충주시\",\"괴산군\",\"단양군\",\"보은군\",\"영동군\",\"옥천군\",\"음성군\",\"증평군\",\"진천군\",\"청원군\"];\r\n");
      out.write("\t   var gugun11 = [\"계룡시\",\"공주시\",\"논산시\",\"보령시\",\"서산시\",\"아산시\",\"천안시\",\"금산군\",\"당진군\",\"부여군\",\"서천군\",\"연기군\",\"예산군\",\"청양군\",\"태안군\",\"홍성군\"];\r\n");
      out.write("\t   var gugun12 = [\"군산시\",\"김제시\",\"남원시\",\"익산시\",\"전주시\",\"정읍시\",\"고창군\",\"무주군\",\"부안군\",\"순창군\",\"완주군\",\"임실군\",\"장수군\",\"진안군\"];\r\n");
      out.write("\t   var gugun13 = [\"광양시\",\"나주시\",\"목포시\",\"순천시\",\"여수시\",\"강진군\",\"고흥군\",\"곡성군\",\"구례군\",\"담양군\",\"무안군\",\"보성군\",\"신안군\",\"영광군\",\"영암군\",\"완도군\",\"장성군\",\"장흥군\",\"진도군\",\"함평군\",\"해남군\",\"화순군\"];\r\n");
      out.write("\t   var gugun14 = [\"경산시\",\"경주시\",\"구미시\",\"김천시\",\"문경시\",\"상주시\",\"안동시\",\"영주시\",\"영천시\",\"포항시\",\"고령군\",\"군위군\",\"봉화군\",\"성주군\",\"영덕군\",\"영양군\",\"예천군\",\"울릉군\",\"울진군\",\"의성군\",\"청도군\",\"청송군\",\"칠곡군\"];\r\n");
      out.write("\t   var gugun15 = [\"거제시\",\"김해시\",\"마산시\",\"밀양시\",\"사천시\",\"양산시\",\"진주시\",\"진해시\",\"창원시\",\"통영시\",\"거창군\",\"고성군\",\"남해군\",\"산청군\",\"의령군\",\"창녕군\",\"하동군\",\"함안군\",\"함양군\",\"합천군\"];\r\n");
      out.write("\t   var gugun16 = [\"서귀포시\",\"제주시\",\"남제주군\",\"북제주군\"];\r\n");
      out.write("\t\r\n");
      out.write("\t\t// 초기 select 설정\r\n");
      out.write("    $(function(){  \t  \r\n");
      out.write(" \t  \t $(\"#sidoSelect\").each(function() {\r\n");
      out.write("\t \t\t  \tfor(var i = 0; i < sidoArea.length; ++i) {\r\n");
      out.write("\t \t\t  \t\t$(this).append(\"<option value='\"+sidoArea[i]+\"'>\"+sidoArea[i]+\"</option>\");\r\n");
      out.write("\t \t\t  \t}\t\t\r\n");
      out.write(" \t\t \t });\t  \t \r\n");
      out.write(" \t \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("\t\t// 시 도 체크시\r\n");
      out.write("    $(\"#sidoSelect\").on(\"change\", function(){\r\n");
      out.write("    \tconsole.log($(\"#sidoSelect option:selected\").val());\r\n");
      out.write("    \t$(\"#gugunSelectArea\").empty();\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar sidoIndex = $(\"#sidoSelect option\").index($(\"#sidoSelect option:selected\"));\r\n");
      out.write("    \t\r\n");
      out.write("    \tconsole.log(sidoIndex);\r\n");
      out.write("\r\n");
      out.write("    \t// 서울\r\n");
      out.write("    \tif(sidoIndex == 1) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun1.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t  */ \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun1[j] + \">\" + gugun1[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 인천\r\n");
      out.write("    \tif(sidoIndex == 2) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun2.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t  */ \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun2[j] + \">\" + gugun2[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 대전\r\n");
      out.write("    \tif(sidoIndex == 3) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun3.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun3[j] + \">\" + gugun3[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 광주\r\n");
      out.write("    \tif(sidoIndex == 4) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun4.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun4[j] + \">\" + gugun4[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 대구\r\n");
      out.write("    \tif(sidoIndex == 5) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun5.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t  */ \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun5[j] + \">\" + gugun5[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 울산\r\n");
      out.write("    \tif(sidoIndex == 6) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun6.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t  */ \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun6[j] + \">\" + gugun6[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 부산\r\n");
      out.write("    \tif(sidoIndex == 7) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun7.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun7[j] + \">\" + gugun7[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 경기도\r\n");
      out.write("    \tif(sidoIndex == 8) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun8.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t  */ \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun8[j] + \">\" + gugun8[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 강원도\r\n");
      out.write("    \tif(sidoIndex == 9) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun9.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun9[j] + \">\" + gugun9[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 충청북도\r\n");
      out.write("    \tif(sidoIndex == 10) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun10.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun10[j] + \">\" + gugun10[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 충청남도\r\n");
      out.write("    \tif(sidoIndex == 11) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun11.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t  */ \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun11[j] + \">\" + gugun11[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 전라북도\r\n");
      out.write("    \tif(sidoIndex == 12) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun12.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun12[j] + \">\" + gugun12[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 전라남도\r\n");
      out.write("    \tif(sidoIndex == 13) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun13.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun13[j] + \">\" + gugun13[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 경상북도\r\n");
      out.write("    \tif(sidoIndex == 14) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun14.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun14[j] + \">\" + gugun14[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 경상남도\r\n");
      out.write("    \tif(sidoIndex == 15) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun15.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  } */\t  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun15[j] + \">\" + gugun15[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t// 제주도\r\n");
      out.write("    \tif(sidoIndex == 16) {\r\n");
      out.write("    \t\tfor(var j = 0; j < gugun16.length; ++j) {\r\n");
      out.write("/* \t \t\t\t\tif(j % 2 == 0) {\r\n");
      out.write("\t\t\t  \t\t\t$(\"#gugunSelectArea\").append(\"<br>\");\r\n");
      out.write("\t  \t\t  }\t */  \t\t\t\t\r\n");
      out.write("\t  \t\t  $(\"#gugunSelectArea\").append(\"<label><input type='checkbox' name='gugunSelect' class='gugunSelect' value=\" + gugun16[j] + \">\" + gugun16[j] +\"</label>\");\t  \t\t\t\r\n");
      out.write(" \t\t\t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t});\r\n");
      out.write("    \r\n");
      out.write("    // 시 도 체크시\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
